### ISSUE TITLE
Sequence Length Limit

### ISSUE THREAD

**Issue by drewnutt** [patrickbryant1/Umol#1]
Looking at the Colab notebook, there seems to be a sequence length limit of 400. However, this is not apparent anywhere else in the code or manuscript. 

Where does this limit come from? Is it only due to computational constraints (i.e. VRAM)? Can this limit be surpassed with larger GPUs?

**Comment by patrickbryant1** [comment]
Hi, the sequence limit is only in the Colab (and only for visualisation reasons). We show the chosen target positions on a structure generated with ESMFold which has a sequence limit of 400 AA for the web API. Umol has no size limit - depending on RAM.

Hope this helps!
