### ISSUE TITLE
When run the 'predict.sh', how to use GPU to accelerate it

### ISSUE THREAD

**Issue by CykaZH** [patrickbryant1/Umol#13]
My machine has a powerful GPU, but the CPU is not very good. When running localcolabfold, I enabled GPU acceleration and the performance was great. So I want to ask if this script can be accelerated by the GPU

**Comment by CykaZH** [comment]
My machine has a powerful GPU, but the CPU is not very good. When running localcolabfold, I enabled GPU acceleration and the performance was great. So I want to ask if this script can be accelerated by the GPU

**Comment by patrickbryant1** [comment]
Yes, this should be automatic if you follow the installation instructions (GPU compatible packages are installed).
