### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (19,19) (2861,2861)

### ISSUE THREAD

**Issue by AlvinLeopold** [patrickbryant1/Umol#14]
Hi there, 
Thanks for your guys develop such powerful tool.

Actually, I have some models predicted by colabfold, to make sure the data consistency, I decided use my own model on Umol.
But when I tried to upload my own Model predicted by colabfold, I recieve the error in this step, btw, I could foud the "_pred_raw.pdb" file were generated, but "generate_best_conformer" seems like could not handle it.
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-10-7f299405357b>](https://localhost:8080/#) in <cell line: 9>()
    107     #Get a conformer
    108     pred_ligand = read_pdb(RAW_PDB)
--> 109     best_conf, best_conf_pos, best_conf_err, atoms, nonH_inds, mol, best_conf_id  = generate_best_conformer(pred_ligand['chain_coords'], LIGAND)
    110 
    111     #Align it to the prediction

[/content/Umol/src/relax/align_ligand_conformer_colab.py](https://localhost:8080/#) in generate_best_conformer(pred_coords, ligand_smiles)
    102         nonH_pos = pos[nonH_inds]
    103         conf_dmat = np.sqrt(1e-10 + np.sum((nonH_pos[:,None]-nonH_pos[None,:])**2,axis=-1))
--> 104         err = np.mean(np.sqrt(1e-10 + (conf_dmat-pred_dmat)**2))
    105         conf_errs.append(err)
    106 

ValueError: operands could not be broadcast together with shapes (19,19) (2861,2861)`

Any advice would be helpful,
Best regard !

**Comment by AlvinLeopold** [comment]
`
import sys, os
from google.colab import files
import pandas as pd
import numpy as np
import py3Dmol

df = pd.read_csv('/content/drive/MyDrive/MetrixOfSM_fix1.csv')

for id in df['ID']:
    ligand = df[df['ID']==id]['ligand'].values[0]
    sequence = df[df['ID']==id]['seqence'].values[0]
    positions = df[df['ID']==id]['position'].values[0]
    #print(id,ligand,sequence,positions)

    if not os.path.exists('content/drive/MyDrive/ULGre/fasta/'+id+'.fasta'):
        #make fasta file
        with open('/content/drive/MyDrive/ULGre/fasta/'+id+'.fasta','w') as f:
            f.write('>'+id+'\n')
            f.write(sequence+'\n')

    if not os.path.exists('/content/drive/MyDrive/ULGre/pocket/'+id+'.npy'):
        #make pocket file
        with open('/content/drive/MyDrive/ULGre/pocket/'+id+'.npy','w') as f:
            f.write(positions+'\n')

    sys.path.insert(0,'/content/Umol/src')
    test_case = False
    ID = id
    LIGAND = ligand
    SEQUENCE = sequence
    TARGET_POSITIONS = positions
    TARGET_POSITIONS = np.array([int(x) for x in TARGET_POSITIONS.split(',')])
    NUM_RECYCLES = 3
    OUTDIR="/content/drive/MyDrive/ULGre/output/"+ID
    if not os.path.exists(OUTDIR):
      os.mkdir(OUTDIR)

    #Write fasta
    with open('/content/'+ID+'.fasta', 'w') as file:
      file.write('>'+ID+'\n')
      file.write(SEQUENCE)
    FASTA_FILE='/content/'+ID+'.fasta'

    #Check MSA
    MSA='/content/ULGre/output'+ID+'.a3m'


    print('Using ligand:', LIGAND)
    #print('Using MSA:' ,MSA)
    print('Using',NUM_RECYCLES,'recycles')

    #Visualise with ESMFold
    #if not os.path.exists(OUTDIR+'/'+ID+'_esmfold.pdb'):
      #!curl -k -X POST --data $SEQUENCE  https://api.esmatlas.com/foldSequence/v1/pdb/ >> $OUTDIR/$ID'_esmfold.pdb'


    view = py3Dmol.view(js='https://3dmol.org/build/3Dmol.js',)
    view.addModel(open("/content/drive/MyDrive/ULGre/output/"+ID+"_esmfold.pdb",'r').read(),'pdb')
    view.setStyle({'chain':'A'},{'cartoon': {'color':'green'}})
    #Highlight
    with open("/content/drive/MyDrive/ULGre/output/"+ID+"_esmfold.pdb","r") as ifile:
        system = "".join([x for x in ifile])
    i = 0
    for line in system.split("\n"):
        split = line.split()
        if len(split) == 0 or split[0] != "ATOM":
            continue
        idx = int(split[5])
        if idx in TARGET_POSITIONS:
            color = "green"
            view.setStyle({'model': -1, 'serial': i+1}, {"stick": {'color': color}})
        i += 1

    view.zoomTo()
    view.show()

    print('The target structure is in cartoon and the target positions (pocket) in stick format.')

    #Subtract 1 from the target positions to make them zero indexed
    TARGET_POSITIONS -= 1

    if not os.path.exists('/content/params40000.npy'):
      print('Getting Umol network parameters.')
      #!wget https://zenodo.org/records/10048543/files/params40000.npy
      !wget https://zenodo.org/records/10397462/files/params40000.npy

    from net.model import config
    from predict_colab import predict
    import numpy as np
    MSA_FEATS='/content/drive/MyDrive/ULGre/output/'+ID+'/msa_features.pkl'
    LIGAND_FEATS='/content/drive/MyDrive/ULGre/output/'+ID+'/ligand_inp_features.pkl'
    PARAMS=np.load('/content/params40000.npy', allow_pickle=True)

    #Predict
    predict(config.CONFIG,
                MSA_FEATS,
                LIGAND_FEATS,
                ID,
                TARGET_POSITIONS,
                PARAMS,
                NUM_RECYCLES,
                outdir='/content/drive/MyDrive/ULGre/output/')
    
    from relax.align_ligand_conformer_colab import read_pdb, generate_best_conformer, align_coords_transform, write_sdf
    import pandas as pd
    RAW_PDB='/content/drive/MyDrive/ULGre/output/'+ID+'_pred_raw.pdb'
    #Get a conformer
    pred_ligand = read_pdb(RAW_PDB)
    best_conf, best_conf_pos, best_conf_err, atoms, nonH_inds, mol, best_conf_id  = generate_best_conformer(pred_ligand['chain_coords'], LIGAND)

    #Align it to the prediction
    aligned_conf_pos = align_coords_transform(pred_ligand['chain_coords'], best_conf_pos, nonH_inds)

    #Write sdf
    write_sdf(mol, best_conf, aligned_conf_pos, best_conf_id, OUTDIR+ID+'_pred_ligand.sdf')
    !grep ATOM $RAW_PDB > $OUTDIR/$ID'_pred_protein.pdb'

    #Ligand plDDT
    !grep HETATM $RAW_PDB| cut -c65-66 > $OUTDIR/ligand_plddt.csv

    ligand_plddt = pd.read_csv(OUTDIR+'ligand_plddt.csv', header=None)

    #@title Download unrelaxed results
    from google.colab import files
    files.download(OUTDIR+ID+"_pred_ligand.sdf")
    files.download(OUTDIR+ID+"_pred_protein.pdb")

    #@title Download unrelaxed results
    from google.colab import files
    files.download(OUTDIR+ID+"_pred_ligand.sdf")
    files.download(OUTDIR+ID+"_pred_protein.pdb")
`
Plus, this is my code for colab.

I'ven tried the offline version, but it keep return the error like this "jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 4975263744 bytes.
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these." Although I set "os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'"

I'm actually found that the RAM usage up to 12.5Gb on colab, unfortunatelly I'm using RTX2080Ti 12Gb, so the colab seems like a good choice temporarily.

**Comment by patrickbryant1** [comment]
Hi,

It appears you have some big shape mismatches here. I am not sure why this, but suggest making sure you are using the same protein and ligands at all steps.

**Comment by AlvinLeopold** [comment]
Thanks for your replied!

Now, I can predict them on colab notebook. But I still have some problem on local.

Mainly about the process of "convert id_esmfold.pdb to id_pred_raw.pdb"

The <predict.py> script seems like dont need input pdb structure file, does it can predict automatically? Or did I missed someting?

**Comment by patrickbryant1** [comment]
Hi, great.
No PDB structure is needed as input - only your protein sequence and ligand SMILES string. See the example.
Hope this helps!
