### ISSUE TITLE
Selection of the interaction sites and pLDTT score

### ISSUE THREAD

**Issue by velocirraptor23** [patrickbryant1/Umol#15]
Hi Patrick,

I was wondering what in your experience would be a good selection on the interaction sites. I have noticed a selection has an impact on the outcome, for instance between 10 and 7 A. Another question would be if I test different sites from the same protein, the pLDTT could give a kind of score about the probably binding site?

Thanks a lot,

Cesar

**Comment by patrickbryant1** [comment]
Hi Cesar,

I think your reasoning is correct. Note that we have added a pocket-free version of Umol that you can try also. The pocket version should be better though.

Hope this helps!

Patrick

**Comment by velocirraptor23** [comment]
Hi, Thanks for your answer. What would be different with pocket-free, Does it sample the whole protein?

**Comment by patrickbryant1** [comment]
Yes, see https://github.com/patrickbryant1/Umol/blob/master/predict.sh.
I would still define the target site and use the pocket version though - just a tip.

**Comment by velocirraptor23** [comment]
Thanks for your reply. I close this tread now.

Best wishes,

Cesar
