### ISSUE TITLE
colab notebook error in prediction step

### ISSUE THREAD

**Issue by biotech70** [patrickbryant1/Umol#16]
Hi, I am trying to predict the binding state of a protein-ligand complex, but in the prediction step. 
![umol](https://github.com/patrickbryant1/Umol/assets/73783725/757b046e-8616-4b26-b77c-5ea92311fb33)

**Comment by patrickbryant1** [comment]
You are not showing any error messages here.
What is the issue?

**Comment by biotech70** [comment]
error was shared.
![error](https://github.com/patrickbryant1/Umol/assets/73783725/dc9da146-f6d9-4eac-b9b1-dc1deaece7c6)

**Comment by patrickbryant1** [comment]
Hi, 
As you can see you have run out of RAM. Try cropping the protein to make it smaller or install the local version if you have your own GPU.

**Comment by biotech70** [comment]
the length of my protein is about 300 residues.

**Comment by patrickbryant1** [comment]
Hi, 
That should be fine. Try to rerun the notebook in a new session.

**Comment by biotech70** [comment]
The problem still persists.

**Comment by patrickbryant1** [comment]
You probably need more RAM in that case. I will close this issue as it is not directly related to any issues with Umol, but rather to your available hardware.
