### ISSUE TITLE
Predict the protein-ligand structure Error

### ISSUE THREAD

**Issue by SarahKnapp1** [patrickbryant1/Umol#2]
Hello, 
I am trying to run on the  Colab 
With the Input: ID:1ct9_happy
LIGAND: OC(=O)CC(C(=O)O)N 
SEQUENCE:DDLQGMFAFALYDSEKDAYLIGRDHLGIIPLYMGYDEHGQLYVASEMKALVPVCRTIKEFPAGSYLWSQDGEIRSYYHRDWFDYDAVKDNVTDKNELRQALEDSVKSHLMSDVPYGVLLSGGLDSSIISAITKKYAARRVEDQERSEAWWPQLHSFAVGLPGSPDLKAAQEVANHLGTVHHEIHFTVQEGLDAIRDVIYHIETYDVTTIRASTPMYLMSRKIKAMGIKMVLSGEGSDEVFGGYLYFHKAPNAKELHEETVRKLLALHMYDCARANKAMSAWGVEARVPFLDKKFLDVAMRINPQDKMCGNGKMEKHILRECFEAYLPASVAWRQKEQFSDGVGYSWIDTLKEVAAQQVSDQQLETARFRFPYNTPTSKEAYLYREIFEELFPLPSAAECVPGGPSVACSSAKAIEWDEAFKKMDDPSGRAVGVHQSAYK
TARGET_POSITIONS:117,120,144,178
NUM_RECYCLES:3
When I try to run my example I get the error in the Predict the protein-ligand structure section :
XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 13608450984 bytes.
BufferAssignment OOM Debugging. (I am running on GPU) 

Can you help me resolve this problem please?

**Comment by patrickbryant1** [comment]
Hi Sarah,

OOM means Out Of Memory. The resources online are limited and you need more RAM. Try to crop the protein sequence around your region of interest (117,120,144,178) and run again. Note that you need to update the target positions and your MSA to match the new cropped sequence. 

Hope this helps!
