### ISSUE TITLE
Some question about giant Protein

### ISSUE THREAD

**Issue by AlvinLeopold** [patrickbryant1/Umol#21]
Hi Mr Bryant:

When I tried to predicte some huge proteins (about 1179 aminos)
It return  error like below:
`XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to allocate 45026377728 bytes.`

I've ran the code at Tesla A100 GPU and tried set `os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'` 
but it still return same error.

May I ask if you have any good advice on this? For example, predicting in parts, but I'm not sure if this will affect the prediction accuracy?

Any response would be helpful
Gratefully!

**Comment by patrickbryant1** [comment]
Hi,

Yes, it seems that you are out of RAM.

Try cropping the protein around the region of interest. Umol is trained on linear crops of 256 residues so it should work well.

Hope this helps!

Patrick
