### ISSUE TITLE
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1313,) + inhomogeneous part.

### ISSUE THREAD

**Issue by sgrigna79** [patrickbryant1/Umol#25]
I'm trying to use colab to generate a protein ligand complex but I got the error in the title..

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (1313,) + inhomogeneous part.

Any idea about the origin?

Thanks 

Jacopo

**Comment by patrickbryant1** [comment]
Hi,

This issue generally comes from shape mismatches. Please make sure all sequences in the msa etc are of equal lengths.

Best,

Patrick
