### ISSUE TITLE
Error 'bash predict.sh'

### ISSUE THREAD

**Issue by Dong-HoSeo** [patrickbryant1/Umol#26]
Source 'gaff-2.11' could not be read. If this is a file, ensure that the path is correct.
Looked in the following paths and found no files named 'gaff-2.11':
    /home/dhseo/Data_HDD2/Umol
    /home/dhseo/mambaforge/envs/umol/lib/python3.12/site-packages/openff/amber_ff_ports/offxml
    /home/dhseo/mambaforge/envs/umol/lib/python3.12/site-packages/smirnoff99frosst/offxml
    /home/dhseo/mambaforge/envs/umol/lib/python3.12/site-packages/openforcefields/offxml
If 'gaff-2.11' is present as a file, ensure it is in a known SMIRNOFF encoding.
Valid formats are: ['XML']
Parsing failed while trying to parse source as a file with the following exception and message:
<class 'openff.toolkit.utils.exceptions.SMIRNOFFParseError'>
syntax error: line 1, column 0

Traceback (most recent call last):
  File "/home/dhseo/Data_HDD2/Umol/./src/relax/openmm_relax.py", line 180, in <module>
    system_generator = SystemGenerator(
                       ^^^^^^^^^^^^^^^^
  File "/home/dhseo/mambaforge/envs/umol/lib/python3.12/site-packages/openmmforcefields/generators/system_generators.py", line 269, in __init__
    raise GAFFNotSupportedError(
openmmforcefields.generators.template_generators.GAFFNotSupportedError: This release (0.13.x) of openmmforcefields temporarily drops GAFF support and thereby the GAFFTemplateGenerator class. Support will be re-introduced in future releases (0.14.x). To use this class, install version 0.12.0 or older.
/home/dhseo/mambaforge/envs/umol/lib/python3.12/site-packages/Bio/PDB/PDBParser.py:395: PDBConstructionWarning: Ignoring unrecognized record 'END' at line 1249
  warnings.warn(
Traceback (most recent call last):
  File "/home/dhseo/Data_HDD2/Umol/./src/relax/add_plddt_to_relaxed.py", line 111, in <module>
    relaxed_coords, relaxed_chains, relaxed_atom_numbers,  relaxed_3seq, relaxed_resnos, relaxed_atoms, relaxed_bfactors = read_pdb(args.relaxed_complex[0])
                                                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dhseo/Data_HDD2/Umol/./src/relax/add_plddt_to_relaxed.py", line 28, in read_pdb
    f=open(pdbname,'rt')
      ^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/test_case/7NB4//7NB4_relaxed_complex.pdb'
The final relaxed structure can be found at ./data/test_case/7NB4//7NB4'_relaxed_plddt.pdb'

**Comment by patrickbryant1** [comment]
Hi,

It seems that you are missing files here. Make sure all the predictions are generated before proceeding to the next step.
