### ISSUE TITLE
About the num_ligand_atoms

### ISSUE THREAD

**Issue by fuxuliu** [patrickbryant1/Umol#34]
Hi, patrick

I noticed that you made some changes in residue_constant to add ligand atom default information to rigid group, but why `num_ligand_atoms=8`
​
When we coded ligand atom, we were supposed to have 11 atom types, right?
```
atom_encoding = {'B':0, 'C':1, 'F':2, 'I':3, 'N':4, 'O':5, 'P':6, 'S':7,'Br':8, 'Cl':9, #Individual encoding
                'As':10, 'Co':10, 'Fe':10, 'Mg':10, 'Pt':10, 'Rh':10, 'Ru':10, 'Se':10, 'Si':10, 'Te':10, 'V':10, 'Zn':10 #Joint (rare)
                 }
```

**Comment by patrickbryant1** [comment]
Hi,

Can you please provide some more information about your issue/where is the problem?

Best,

Patrick

**Comment by patrickbryant1** [comment]
I will close this issue due to inactivity.
