### ISSUE TITLE
Why are the following packages not available from the current channels?

### ISSUE THREAD

**Issue by mrqfliu** [patrickbryant1/Umol#35]
*****$ bash install_dependencies.sh
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - ld_impl_linux-64==2.38=h1181459_1
  - intel-openmp==2023.1.0=hdb19cb5_46306
  - libjpeg-turbo==3.0.0=hd590300_1
  - lz4-c==1.9.4=hcb278e6_0
  - krb5==1.21.2=h659d440_0
  - re2==2023.06.02=h2873b5e_0
  - xorg-renderproto==0.11.1=h7f98852_1002
  - tornado==6.3.3=py312h98912ed_1
  - wheel==0.41.2=py312h06a4308_0
  - debugpy==1.8.0=py312h30efb56_1
  - xorg-libxrender==0.9.11=hd590300_0
  - mkl_random==1.2.4=py312hdb19cb5_0
  - toolz==0.12.0=py312h06a4308_0
  - libre2-11==2023.06.02=h7a70373_0
  - openmm==8.1.0=py312hc343695_1
  - bzip2==1.0.8=h7b6447c_0
  - ca-certificates==2023.11.17=hbcca054_0
  - sqlalchemy==2.0.23=py312h98912ed_0
  - yaml==0.2.5=h7f98852_2
  - numexpr==2.8.7=py312hf827012_0
  - zeromq==4.3.5=h59595ed_0
  - libaec==1.1.2=h59595ed_1

**Comment by patrickbryant1** [comment]
Hi,

Try installing the packages with pip. The channels and available packages are constantly updated and we are doing our best to update the code/installation accordingly. 

If you build with the specified dependencies, it will work.

Best,

Patrick
