### ISSUE TITLE
Request for Training Details of the Mode

### ISSUE THREAD

**Issue by 124189** [patrickbryant1/Umol#36]
Hi Patrick,

I hope this message finds you well. I’m currently exploring your model and am impressed with its capabilities. I would like to request more details regarding the training process—specifically, any insights on the training data, training duration, and the optimization methods used.

Your guidance would be greatly appreciated, as it will help me better understand the model's performance and applicability to my own work.

Thank you for your time!

Best,
Jason

**Comment by patrickbryant1** [comment]
Hi,

All of the details can be found in the methods section here: https://www.nature.com/articles/s41467-024-48837-6

Best,

Patrick
