### ISSUE TITLE
How do I get the plddt score

### ISSUE THREAD

**Issue by vecos1990** [patrickbryant1/Umol#37]
Dear Patrick, thank you for this remarkable resource.

I would be happy to know how I can get the plddt score.
After my prediction (Locally), the only .csv file I see is the conformer_dmat_err.csv.

I wonder if the score is written in another file, and if so, how can I get it?

Best regards

**Comment by patrickbryant1** [comment]
Hi,

Glad to hear you like Umol. You can get the plDDT by doing:
#Ligand plDDT
grep HETATM $RAW_PDB| cut -c65-66 > $OUTDIR/ligand_plddt.csv

Where RAW_PDB is the path to your predicted file.
This will provide plDDT per position into a csv and you can then manipulate this as you see fit.

Hope this helps!

Best,

Patrick

**Comment by vecos1990** [comment]
Thank you so much.
