### ISSUE TITLE
Multiple chains in protein sequence

### ISSUE THREAD

**Issue by rajatpunia** [patrickbryant1/Umol#4]
Thanks for sharing the Umol code, it is a highly helpful resource. I want to try it on a protein with multiple (4) chains. Each chain contains around 900 residues and ligand interacts with residues from all 4 chains. I want to use only a subset of residues near the binding site as an input sequence. Is it possible to run Umol for such a case? If yes, how can i do it? e.g. what should be the format of sequence for MSA and Umol?

**Comment by patrickbryant1** [comment]
Hi, we have not added this possibility. You can try to make paired MSAs and concatenate the full sequence. This should work in principle, but we have not tried.
