### ISSUE TITLE
limit in protein length or msa sequence number?

### ISSUE THREAD

**Issue by Yogesh1-11** [patrickbryant1/Umol#5]
hi as a test case i was using a protein of 539 residue lenth and msa of 25 protein sequences. 
but i am getting memory exhaustion error. Is colab limited to protein length or msa size?

**Comment by patrickbryant1** [comment]
Hi, the limit is on protein length. A statistical representation is created from the MSA and the size of this thereby doesn't matter. However, 25 sequences is probably too shallow to get good results.

**Comment by Yogesh1-11** [comment]
even after chopping protein length  to 490 error persists. what is the
maximum protein length for umol? Also, I am using ion(

[O-]P(=O)([O-])[O-]) as ligand.


---------------------------------------------------------------------------

XlaRuntimeError                           Traceback (most recent call last)

<ipython-input-6-55efa3eb56f8> <https://localhost:8080/#> in <cell
line: 10>()      8       9 #Predict
---> 10 predict(config.CONFIG,     11             MSA_FEATS,     12
         LIGAND_FEATS,


------------------------------
9 frames
------------------------------

    [... skipping hidden 14 frame]


/usr/local/lib/python3.10/dist-packages/jax/_src/dispatch.py
<https://localhost:8080/#> in backend_compile(backend, built_c,
options, host_callbacks)   1010   # TODO(sharadmv): remove this
fallback when all backends allow `compile`   1011   # to take in
`host_callbacks`
-> 1012   return backend.compile(built_c, compile_options=options)
1013    1014 # TODO(phawkins): update users.


XlaRuntimeError: RESOURCE_EXHAUSTED: Out of memory while trying to
allocate 8274444288 bytes.

**Comment by patrickbryant1** [comment]
This depends on the available RAM. Umol has no limit. I don't know what you have available in Colab, but recommend to run it locally for bigger proteins. We have not trained on phosphorylation sites.
