### ISSUE TITLE
Different models

### ISSUE THREAD

**Issue by velocirraptor23** [patrickbryant1/Umol#8]
Hi,

I was wondering if there is any way it can be generated a number of good ranked models, As of now I only get one model, but I can see the model sometimes gives a bad pose. Just wondering if it is possible to generate more than one pose with different rankings. or the other way is to have control of the parameters to get a different result. Well, I dont know well the code, better to ask. Great tool by the way, in other cases this approach works really well.

Best wishes,

Cesar

**Comment by patrickbryant1** [comment]
Hi,

You can run Umol many times (e.g. 10) and use the average ligand plddt for ranking. Each run, slightly different information is sampled leading to slightly different outcomes.

Another option is to increase the number of recycles.

Umol will only give good results in 45% of cases (on average) and this depends on the ligands as well. If these have high affinity, it is more likely to get an accurate pose.

Hope this helps!
